# a stack, where the last element added is the first element retrieved (“last-in, first-out”)
stack = [3,4,5]
print(f"original stack {stack}")
stack.append(6)
stack.append(7)
print(f"stack after adding 6, 7: {stack}")
x = stack.pop()
print(f"popped element 1: {x}")
print(f"stack after pop: {stack}")
x = stack.pop()
print(f"popped element 2: {x}")
print(f"stack after pop: {stack}")
x = stack.pop()
print(f"popped element 3: {x}")
print(f"stack after pop: {stack}")